# Generated by Django 5.1.1 on 2024-10-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_phone_number_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
