# Generated by Django 5.1.1 on 2024-10-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'item_title')},
        ),
    ]
