# Generated by Django 5.1.1 on 2024-10-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrecord',
            name='search_link',
            field=models.URLField(default=''),
        ),
    ]
